services:
  retail-ram-miner:
    build:
      context: .
      dockerfile: Dockerfile
    image: us-central1-docker.pkg.dev/retail-ram-miner/miner-repo/crawler:latest

    container_name: retail-ram-miner

    volumes:
        - ./data:/app/data